### ISSUE TITLE
java.lang.NoClassDefFoundError :  org/webrtc/CameraVideoCapturer$CameraEventsHandler

### ISSUE THREAD

**Issue by guidorubin** [dkornev/TwilioVideoXamarinAndroid#6]
Hi! 

Im getting an error when building a project with Azure Devops. 

` Exception in thread "main" java.lang.NoClassDefFoundError: org/webrtc/CameraVideoCapturer$CameraEventsHandler
  	at java.lang.ClassLoader.defineClass1(Native Method)
  	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
  	at java.lang.ClassLoader.defineClass(ClassLoader.java:642)
  	at com.google.devtools.build.android.desugar.HeaderClassLoader.findClass(HeaderClassLoader.java:66)
  	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
  	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
  	at com.google.devtools.build.android.desugar.LambdaDesugaring.loadFromInternal(LambdaDesugaring.java:330)
  	at com.google.devtools.build.android.desugar.LambdaDesugaring.access$500(LambdaDesugaring.java:53)
  	at com.google.devtools.build.android.desugar.LambdaDesugaring$InvokedynamicRewriter.createLookup(LambdaDesugaring.java:559)
  	at com.google.devtools.build.android.desugar.LambdaDesugaring$InvokedynamicRewriter.visitInvokeDynamicInsn(LambdaDesugaring.java:395)
  	at org.objectweb.asm.ClassReader.a(Unknown Source)
  	at org.objectweb.asm.ClassReader.b(Unknown Source)
  	at org.objectweb.asm.ClassReader.accept(Unknown Source)
  	at org.objectweb.asm.ClassReader.accept(Unknown Source)
  	at com.google.devtools.build.android.desugar.Desugar.desugarClassesInInput(Desugar.java:401)
  	at com.google.devtools.build.android.desugar.Desugar.desugarOneInput(Desugar.java:326)
  	at com.google.devtools.build.android.desugar.Desugar.desugar(Desugar.java:280)
  	at com.google.devtools.build.android.desugar.Desugar.main(Desugar.java:584)
  Caused by: java.lang.ClassNotFoundException: Class org.webrtc.CameraVideoCapturer$CameraEventsHandler not found
  	at com.google.devtools.build.android.desugar.HeaderClassLoader.findClass(HeaderClassLoader.java:53)
  	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
  	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
  	... 18 more`

Any idea?

**Comment by dkornev** [comment]
Hi,

Please provide more details. What binding version are you using? Xamarin.Android version?
Have you tried building the app locally?

**Comment by guidorubin** [comment]
Hi Dkornev! Thanks for answering. 

Im using Twilio Video Xamarin Android 4.3.0 and Xamarin.Android 9.4.1.0

Locally builds perfect.

**Comment by dkornev** [comment]
Check the differences between your _debug_ and _release_ configurations.  What are the values for the following properties:
- TargetFrameworkVersion
- EnableProguard
- AndroidLinkMode
- AndroidDexTool
- AndroidLinkTool

Are you sure that you use correct _ proguard_ settings?

It might be a code-linking or code-shrinking problem

**Comment by guidorubin** [comment]
Im not using proguard in Xamarin project... 
Anyway I try ... 
`-keep class org.webrtc.** { ; } 
-dontwarn org.webrtc.* 
-keep class com.twilio.video.** { ; }
-keep class com.twilio.common.* { *; } 
-keepattributes InnerClasses`

TargetFrameworkVersion = 9.0
AndroidDexTool try with both dx and d8.

What I can't understand is that it is bulding locally for both debug and release. 

Maybe something wrong with Azure Devops? Any idea of what can I do?

**Comment by dkornev** [comment]
No, I have never had this problem. I personally use AppCenter for CI/CD, but I believe that it should also work fine with Azure Devops

**Comment by dkornev** [comment]
What about AndroidLinkMode?

**Comment by guidorubin** [comment]
<AndroidLinkMode>SdkOnly</AndroidLinkMode> in Release mode. 

Im out of ideas. I tried everything..

**Comment by guidorubin** [comment]
Hi! Anything you think I could try?

**Comment by dkornev** [comment]
Hi.
Unfortunately, I can't reproduce this issue and don't know how to fix this one for you. Have you tried to build an empty android project with this nuget package installed?

**Comment by guidorubin** [comment]
Thanks, no I didn't. 
I will try to do that.

**Comment by guidorubin** [comment]
Update azure vmImage to `windows-latest` and it worked!

**Comment by dkornev** [comment]
Thanks for letting me know
